vich_uploader:
    db_driver: orm

    mappings:
        base_style:
            uri_prefix: /images/base_styles
            upload_destination: '%kernel.project_dir%/public/images/base_styles'


        product:
            uri_prefix: /images/product_images
            upload_destination: '%kernel.project_dir%/public/images/product_images'
